# Generated by Django 5.2.2 on 2025-06-09 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comentario', models.TextField()),
                ('participante', models.ForeignKey(limit_choices_to={'rol': 'CANDIDATO'}, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('evaluado', models.ForeignKey(limit_choices_to={'rol': 'CANDIDATO'}, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('evaluador', models.ForeignKey(limit_choices_to={'rol': 'ADMIN_EVENTO'}, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
