# Generated by Django 5.2.2 on 2025-06-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0002_calificacion_evaluacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('opcion_1', models.CharField(max_length=100)),
                ('opcion_2', models.CharField(max_length=100)),
                ('opcion_3', models.CharField(max_length=100)),
                ('respuesta_correcta', models.PositiveSmallIntegerField(choices=[(1, 'Opción 1'), (2, 'Opción 2'), (3, 'Opción 3')])),
            ],
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='evaluado',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='evaluador',
        ),
        migrations.DeleteModel(
            name='Calificacion',
        ),
        migrations.DeleteModel(
            name='Evaluacion',
        ),
    ]
