# Generated by Django 5.2.2 on 2025-06-09 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0003_pregunta_remove_evaluacion_evaluado_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pregunta',
            new_name='Evaluacion',
        ),
    ]
